# 2023-06-15 Andreas Abel, Agda CI + HTML deployment
name: build
on:
  push:
    branches:
      - master
      - ci-*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22

      - name: Get Agda version
        id: get-agda-version
        run: |
          echo version="$(nix develop .#agda --command agda --version)" >>$GITHUB_OUTPUT
      - name: Cache build
        uses: actions/cache@v3
        id:   cache
        with:
          key: ${{ runner.os }}-${{ steps.get-agda-version.outputs.version }}
          path: _build

      - name: Run Agda
        run: nix develop .#agda --command agda README.agda --html

      - uses: actions/upload-pages-artifact@v1
        with:
          path: html

  # Deploy job, see https://github.com/actions/deploy-pages/tree/f81ad71d2e78487340fb3a94726f2a6050466efd#readme
  deploy:
    if: github.ref == 'refs/heads/master'
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages:    write   # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
    - name: Deploy to GitHub Pages
      id:   deployment
      uses: actions/deploy-pages@v2
